apiVersion: v1
kind: Service
metadata:
  labels:
    app: canary-preview
  name: canary-preview
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: canary
  sessionAffinity: None
  type: ClusterIP
